#!/bin/bash

cd /tmp/

git clone "https://$GITHUB_USERNAME:$GITHUB_PERSONAL_ACCESS_TOKEN@github.com/Indigitous/godtools-web.git"

cd ./godtools-web/

bundle install

bundle exec rake locales:update

bundle exec middleman deploy

